[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "elliptax"
version = "0.1.2"
description = "JAX implementations of elliptic integrals"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"
dependencies = ["jax"]

[tool.setuptools.packages.find]
where = ["."]
include = ["elliptax*"]
